### ISSUE TITLE
--gpu argument is not working

### ISSUE THREAD

**Issue by macramole** [orasanen/ALICE#10]
`pyannote-audio` runs with `--cpu` flag even if `--gpu` is passed to ./run_ALICE.sh

fix:
on ./run_ALICE.sh line 32 should be:
`GPU="gpu";`
and line 47 should read:
`bash $THISDIR/voice-type-classifier/apply.sh $THISDIR/tmp_data/ "MAL FEM" --device=$GPU |& sed '/^Took/d'`

*--device=gpu* argument must be passed instead of *--gpu*

I think this bug was already in last version since my execution time for a 2 hour audio dropped from 70min to 10min

**Comment by orasanen** [comment]
Hmm that's weird. We processed all ACLEW data on a computing cluster specifically using GPUs, but this was with an older version of pyannote. Maybe the syntax has changed. Anyway, fixed!
