### ISSUE TITLE
SED trick doesn't work on MacOS

### ISSUE THREAD

**Issue by orasanen** [orasanen/ALICE#11]
$ sh run_ALICE.sh demo/ 

run_ALICE.sh: line 52: syntax error near unexpected token `&'

run_ALICE.sh: line 52: `bash $THISDIR/voice-type-classifier/apply.sh $THISDIR/tmp_data/ "MAL FEM" $GPU |& sed '/^Took/d''

**Comment by MarvinLvn** [comment]
Seems like `|&` is not compatible with older bash versions.
The last PR should have fixed this issue :)

Source : https://stackoverflow.com/questions/20553916/syntax-error-near-unexpected-token-using
