### ISSUE TITLE
Is run_ALICE.sh running SAD ?

### ISSUE THREAD

**Issue by macramole** [orasanen/ALICE#14]
I have a question regarding ALICE pipeline.

Line 43 and 44 of run_ALICE.sh reads:
```
# Run SAD on the files
python3 prepare_data.py $THISDIR $DATADIR/
```
But after reading _prepare_data.py_ it doesn't look as if it is running any SAD related task.

am I missing something ? does voice-type-classifier run SAD ? it is non mandatory to run SAD before voice-type-classifier ?

Reading the code in _voice-type-classifier/apply.sh_ it runs pyannote-audio with *mlt* parameter which doesn't seem to be running SAD either.

Best regards,
Leandro Garber

**Comment by orasanen** [comment]
Oh, right. The comment can be somewhat confusing. The "SAD" is done jointly on row 49 with speaker diarization, so the voice-type-classifier is responsible for both speech detection and speaker attribution. 

bash $THISDIR/voice-type-classifier/apply.sh $THISDIR/tmp_data/ "MAL FEM" --device=$GPU 2>&1 | sed '/^Took/d'

I have now fixed the comment to be clearer.
