### ISSUE TITLE
building ALICE on Windows

### ISSUE THREAD

**Issue by dan-ya** [orasanen/ALICE#15]
Dear authors,
I've tried to build ALICE on Windows with Anaconda3 environment, but failed with a following message.
Best regards,
Daniil Kocharov

Collecting package metadata (repodata.json): done
Solving environment: failed
ResolvePackageNotFound:
  - lame=3.100
  - readline=8.0
  - sox=14.4.2
  - ncurses=6.1
  - mad=0.15.1b

**Comment by orasanen** [comment]
Dear Daniil,

Unfortunately, ALICE is not currently supported on Windows due to the package compatibility issues. We have developed & tested ALICE on Linux and MacOS.

BR,
Okko
