### ISSUE TITLE
question: desirable time precision, given ALICE workings?

### ISSUE THREAD

**Issue by alecristia** [orasanen/ALICE#17]
From README:

> Timestamps appended to the filenames are of form <onset_time_in_ms x 10> _ <offset_time_in_ms x 10>, as measured from the beginning of each audio file. For instance, _00062740_00096150.wav stands for an utterance in <filename.wav> that started at 6.274 seconds and ended at 9.615 seconds.

So the examples have a millisecond accuracy, but are stored as tenths of milliseconds integers -- does this come from e.g. annotation in ELAN? Is it ideal to keep notations with tenths of ms precision, or can ms precision do?

**Comment by orasanen** [comment]
I think ms precision should be fine. I don't remember why we went for the current solution. Does it cause problems in some context?

**Comment by alecristia** [comment]
not to my knowledge! we are thinking standard notation & were aiming for millisecond precision (but not more).
Thanks!
