### ISSUE TITLE
Error message regarding ./run_ALICE.sh

### ISSUE THREAD

**Issue by rangpark92** [orasanen/ALICE#18]
Hello! I was able to install ALICE on my computer, but have been running into issues using ./run_ALICE.sh command with the provided demo file. Below is the error message I got:

(base) C02DD4H0ML7H:ALICE yerangpark$ conda activate ALICE
(ALICE) C02DD4H0ML7H:ALICE yerangpark$ ./run_ALICE.sh demo/ROS_5271_20_01_03600_snippet_mono.wav
Traceback (most recent call last):
  File "prepare_data.py", line 29, in <module>
    raise Exception('Provided input file list does not exist.')
Exception: Provided input file list does not exist.
ls: /Users/yerangpark/ALICE/tmp_data/*.wav: No such file or directory
The folder you provided doesn't contain any wav files.
Traceback (most recent call last):
  File "split_to_utterances.py", line 14, in <module>
    with open(curdir + '/output_voice_type_classifier/tmp_data/all.rttm') as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/yerangpark/ALICE/output_voice_type_classifier/tmp_data/all.rttm'
getFinalEstimates.py:10: UserWarning: genfromtxt: Empty input file: "/Users/yerangpark/ALICE/tmp_data/features/ALUCs_out_individual.txt"
  F = genfromtxt(curdir + "/tmp_data/features/ALUCs_out_individual.txt", delimiter='\t')
cp: /Users/yerangpark/ALICE/output_voice_type_classifier/tmp_data/all.rttm: No such file or directory
ALICE completed. Results written to /Users/yerangpark/ALICE/ALICE_output.txt and /Users/yerangpark/ALICE/diarization_output.rttm.

I've tried running this code with other audio files and still got the same error message. I double-checked that the files were in the ALICE folder, so I'm not sure why the files can't be located. Any help would be greatly appreciated. Thank you!

**Comment by orasanen** [comment]
Hi!

Thanks for pointing this out!

Not sure when this had appeared, but run_ALICE.sh had an extra slash that caused individual .wavs to be interpreted as folders. 

Made the following change to run_ALICE.sh
python3 prepare_data.py $THISDIR $DATADIR/
-->
python3 prepare_data.py $THISDIR $DATADIR

Should work now! Please let us know if the problem persists.

**Comment by rangpark92** [comment]
Hi, thanks so much for your quick response. I tried the same code (./run_ALICE.sh demo/ROS_5271_20_01_03600_snippet_mono.wav) and got the same error message :( I also tried cd ALICE to set the directory, but it didn't work?

**Comment by orasanen** [comment]
Hi,

I cloned the full repository from scratch, and I'm currently unable to reproduce the error after the update. Can you confirm that your run_ALICE.sh corresponds to the newest version?

BR,
Okko

**Comment by rangpark92** [comment]
It works now, thank you so much!

**Comment by manelkhentout** [comment]
Hello, i have the same problem and im using the version Oct,21 any suggestions please?

**Comment by orasanen** [comment]
@manelkhentout : can you confirm that if you delete, clone, re-install env and run (i.e., install from scratch), the problem persists?

**Comment by manelkhentout** [comment]
yes i delete everything and re-install but the problem persists
