### ISSUE TITLE
ALICE does not handle stereo signals

### ISSUE THREAD

**Issue by orasanen** [orasanen/ALICE#2]
This needs to be fixed.

**Comment by macramole** [comment]
on run_SylNet.py line 98 to 100 it reads:
```
fs, y = scipy.io.wavfile.read(fileList[i])
y = y/max(abs(y))
y = librosa.core.resample(y=y, orig_sr=fs, target_sr=Fs)
```
my suggestion:
```
y, _ = librosa.core.load(fileList[i], sr = Fs, mono = True)
y = y/max(abs(y))
```
This way you are resampling and assuring mono in one line

**Comment by orasanen** [comment]
Hi! Thanks for a great suggestion! This was an issue with SylNet submodule. I have now updated SylNet and added the new version as a submodule to ALICE. 

Please note that ALICE moved from "master" to "new_diarizer" branch, and the update only applies to the new branch.

**Comment by macramole** [comment]
super !
should I `git checkout new_diarizer` and `git submodules update` ?


--
leandrogarber.info

**Comment by orasanen** [comment]
I'm not actually sure if that would work. A lot of things were changed in the main repo + both submodules as I upgraded to an entirely new version of the diarizer at the same time. Also, the whole pyannote tools have to be reinstalled from scratch (see the new ALICE readme). 

I recommend just reinstalling the entire thing from scratch (including the Conda environment), if you want to change the branch. 

Note that the counts from the demo script have also changed, so you can use that to check if things are working correctly or not.
